### ISSUE TITLE
Pushing Pistons Crashes Game

### ISSUE THREAD

**Issue by RyanCR03** [williambl/piston-control#3]
If you use a piston to push/pull a piston the game just completely crashes crash log: https://pastebin.com/j9KUdYN6

**Comment by williambl** [comment]
![2020-07-21_19 28 14](https://user-images.githubusercontent.com/5115825/88092498-182bd680-cb80-11ea-803f-7b1865336318.png)


Cannot reproduce. Could you show me the setup you've built?

**Comment by redstonerblast** [comment]
try making a simple slime machine dude, it dies instantly

**Comment by williambl** [comment]
Still can't reproduce. What kind of machine are you making?

![2020-07-23_15 07 52](https://user-images.githubusercontent.com/5115825/88297275-3f54e600-ccef-11ea-8f67-60596c4c95a0.png)
![2020-07-23_15 15 33](https://user-images.githubusercontent.com/5115825/88297280-40861300-ccef-11ea-9785-c8f7d3242128.png)

**Comment by redstonerblast** [comment]
how the... it does not work for us but for u? i am confused

**Comment by williambl** [comment]
Try this update? https://www.curseforge.com/minecraft/mc-mods/piston-control/files/3013495

**Comment by RyanCR03** [comment]
![image](https://user-images.githubusercontent.com/32957560/88457767-cbc9ea80-ce4e-11ea-9017-f8299c772cd1.png)

**Comment by redstonerblast** [comment]
Nope issue still occurs;

> java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.class_4970$class_4971.handler$zbn000$isBookshelf(class_4970.java:1057)
	at net.minecraft.class_4970$class_4971.method_27852(class_4970.java)
	at net.minecraft.class_2665.method_11484(class_2665.java:246)
	at net.minecraft.class_2674.method_11537(class_2674.java:47)
	at net.minecraft.class_2665.method_11483(class_2665.java:116)
	at net.minecraft.class_2665.method_9612(class_2665.java:91)
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:838)
	at net.minecraft.class_1937.method_8492(class_1937.java:408)
	at net.minecraft.class_1937.method_8508(class_1937.java:388)
	at net.minecraft.class_2426.method_10365(class_2426.java:73)
	at net.minecraft.class_2426.method_9588(class_2426.java:50)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:873)
	at net.minecraft.class_3218.method_14189(class_3218.java:596)
	at net.minecraft.class_3218$$Lambda$4879/209326619.accept(Unknown Source)
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.executeTicks(LithiumServerTickScheduler.java:227)
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.method_8670(LithiumServerTickScheduler.java:73)
	at net.minecraft.class_3218.method_18765(class_3218.java:351)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$4867/767046927.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_4970$class_4971.handler$zbn000$isBookshelf(class_4970.java:1057)
	at net.minecraft.class_4970$class_4971.method_27852(class_4970.java)
	at net.minecraft.class_2665.method_11484(class_2665.java:246)
	at net.minecraft.class_2674.method_11537(class_2674.java:47)
	at net.minecraft.class_2665.method_11483(class_2665.java:116)
	at net.minecraft.class_2665.method_9612(class_2665.java:91)
	at net.minecraft.class_4970$class_4971.method_26181(class_4970.java:838)

-- Block being updated --
Details:
	Source block type: ID #minecraft:observer (block.minecraft.observer // net.minecraft.class_2426)
	Block: Block{minecraft:piston}[extended=false,facing=east]
	Block location: World: (-13,57,4), Chunk: (at 3,3,4 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.class_1937.method_8492(class_1937.java:408)
	at net.minecraft.class_1937.method_8508(class_1937.java:388)
	at net.minecraft.class_2426.method_10365(class_2426.java:73)
	at net.minecraft.class_2426.method_9588(class_2426.java:50)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:873)
	at net.minecraft.class_3218.method_14189(class_3218.java:596)
	at net.minecraft.class_3218$$Lambda$4879/209326619.accept(Unknown Source)

-- Block being ticked --
Details:
	Block location: World: (-12,58,4), Chunk: (at 4,3,4 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.executeTicks(LithiumServerTickScheduler.java:227)
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.method_8670(LithiumServerTickScheduler.java:73)
	at net.minecraft.class_3218.method_18765(class_3218.java:351)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Redstonerblast'/2, l='ServerLevel[Redstone Testing World]', x=-9.57, y=57.38, z=1.43]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,55,8), Chunk: (at 8,3,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 81344 game time, 3421 day time
	Level name: Redstone Testing World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 67123 (now: false), thunder time: 121534 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$4867/767046927.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 826640560 bytes (788 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Patchouli open book context: n/a
	Fabric Mods: 
		advancedchat: AdvancedChat 2.0.5
		archcreatia: Arch Creatia 0.9.4
		auther: Auther 0.2.0-alpha.3-1.16
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		automated_crafting: Automated Crafting 1.1.3+1.16.1
		betternether: Better Nether 3.2.5
		blue_endless_jankson: jankson +
		byg: BYG 1.0.10
		cardinal-components-base: Cardinal Components API (base) 2.4.0
		cardinal-components-entity: Cardinal Components API (entities) 2.4.0
		cavebiomes: Cave Biomes 0.2.3
		cinderscapes: Cinderscapes 1.0.4+build.25
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		cotton: Cotton 1.0.5
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		cotton-resources: Cotton Resources 1.7.1
		diggusmaximus: Diggus Maximus 1.3.0-1.16
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		fabric: Fabric API 0.14.1+build.372-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		fiber: fiber 0.23.0-1
		jankson: Jankson 3.0.0+j1.2.0
		kyrptconfig: Kytpt Config 1.1.0-1.16
		lacrimis: Lacrimis 1.1.3
		libgamerule: LibGamerule ${version}
		libgui: LibGui 2.0.1+1.16.1
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		mdp: MusicDiscsPlus 1.0.0-FABRIC.1.16.1
		minecraft: Minecraft 1.16.1
		mixedslab: Mixed Slab 1.16.1-fabric-1.1.0.1
		modmenu: Mod Menu 1.14.5+build.30
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		origins: Origins 1.16-0.2.3
		patchouli: Patchouli 1.16-38-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		pistoncontrol: Piston Control 1.2.2
		qcommon-croco: Croco 2.1.2
		rare-ice: Rare Ice 0.2.0
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		ring_of_enderchest: Ring of Enderchest 1.0.21
		roughlyenoughitems: Roughly Enough Items 4.10.2
		shapes: Shapes 2.0.0+build.10
		silky_spawners: Silky Spawners 2.0.0+build.1-1.16
		sleepvote: SleepVote ${version}
		sodium: Sodium 0.1.0
		soulbound: Soulbound 1.0.1
		soulsoilfarmland: Soul Soil Farmland 0.0.1
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.3+build.46
		torridvision: Torrid Vision 0.0.1
		traverse: Traverse 2.2.12+build.24
	Player Count: 1 / 8; [class_3222['Redstonerblast'/2, l='ServerLevel[Redstone Testing World]', x=-9.57, y=57.38, z=1.43]]
	Data Packs: vanilla (incompatible), fabric/terrestria, fabric/automated_crafting, fabric/silky_spawners, fabric/betternether, fabric/traverse, fabric/mdp, fabric/cotton-resources, fabric/cotton-commons, fabric/fabric-tool-attribute-api-v1, fabric/archcreatia (incompatible), fabric/lacrimis, fabric/rare-ice, fabric/mostructures, fabric/origins, fabric/soulsoilfarmland, fabric/byg, fabric/cinderscapes, fabric/mixedslab, fabric/ring_of_enderchest, fabric/pistoncontrol
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by redstonerblast** [comment]
Source block type: ID #minecraft:observer (block.minecraft.observer // net.minecraft.class_2426)
	Block: Block{minecraft:piston}[extended=false,facing=east]
	Block location: World: (-13,57,4), Chunk: (at 3,3,4 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.class_1937.method_8492(class_1937.java:408)
	at net.minecraft.class_1937.method_8508(class_1937.java:388)
	at net.minecraft.class_2426.method_10365(class_2426.java:73)
	at net.minecraft.class_2426.method_9588(class_2426.java:50)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:873)
	at net.minecraft.class_3218.method_14189(class_3218.java:596)
	at net.minecraft.class_3218$$Lambda$4879/209326619.accept(Unknown Source)

-- Block being ticked --
Details:
	Block location: World: (-12,58,4), Chunk: (at 4,3,4 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
hmmm

**Comment by redstonerblast** [comment]
it was the observer????

**Comment by redstonerblast** [comment]
Ah it seems to be a confliction with another mod

**Comment by redstonerblast** [comment]
its with almost every mod...
